variables:
  - group: LaPauseClope

trigger:
  - devops

pool:
  name: SelfHosted

stages:
  - stage: TerraformPlan
    displayName: 'Terraform Plan'
    jobs:
      - job: TerraformPlanJob
        displayName: 'Generate Terraform Plan'
        steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "Installing or updating Azure CLI..."

                Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi
                Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet /qn /norestart'

                Write-Host "Azure CLI version after install:"
                az --version
                Write-Host "Checking Terraform version..."
                try { terraform --version } catch { Write-Error "Terraform not found or failed: $_" }
                Write-Host "Checking current directory..."
                Get-Location
                Write-Host "Listing directory contents..."
                Get-ChildItem -Path .
                Write-Host "Checking environment variables..."
                Write-Host "ARM_CLIENT_ID: $env:ARM_CLIENT_ID"
                Write-Host "ARM_TENANT_ID: $env:ARM_TENANT_ID"
                Write-Host "ARM_SUBSCRIPTION_ID: $env:ARM_SUBSCRIPTION_ID"
                Write-Host "ARM_RESOURCE_GROUP_NAME: $env:ARM_RESOURCE_GROUP_NAME"
            displayName: 'Check Environment'
            env:
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
              ARM_RESOURCE_GROUP_NAME: $(ARM_RESOURCE_GROUP_NAME)

          - task: AzureCLI@2
            inputs:
              azureSubscription: PauseClope
              scriptType: ps
              scriptLocation: inlineScript
              inlineScript: |
                Write-Host "Authenticating to Azure using service principal..."
                $tenantId = $env:ARM_TENANT_ID
                $clientId = $env:ARM_CLIENT_ID
                $secret   = $env:ARM_CLIENT_SECRET

                if (-not $tenantId -or -not $clientId -or -not $secret) {
                  Write-Error "Missing one or more Azure credential environment variables."
                  exit 1
                }

                try {
                  az login --service-principal `
                    --username $clientId `
                    --password $secret `
                    --tenant $tenantId `
                    --output none

                  az account show
                  Write-Host "Login successful."
                } catch {
                  Write-Error "Azure login failed: $_"
                  exit 1
                }
            displayName: 'Test Azure Login'
            env:
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
          - task: AzureCLI@2
            inputs:
              azureSubscription: PauseClope
              scriptType: ps
              scriptLocation: inlineScript
              inlineScript: |
                Write-Host "Navigating to terraform directory..."
                try {
                  Set-Location -Path terraform
                  Write-Host "Current directory: $(Get-Location)"
                } catch {
                  Write-Error "Failed to navigate to terraform directory: $_"
                  exit 1
                }
                Write-Host "Running terraform init..."
                try {
                  terraform init -upgrade `
                    -backend-config="resource_group_name=$env:ARM_RESOURCE_GROUP_NAME" `
                    -backend-config="storage_account_name=$env:ARM_STORAGE_ACCOUNT_NAME" `
                    -backend-config="container_name=$env:ARM_CONTAINER_NAME" `
                    -backend-config="access_key=$env:ARM_ACCESS_KEY"
                  Write-Host "Terraform init completed successfully."
                } catch {
                  Write-Error "Terraform init failed: $_"
                  exit 1
                }
            displayName: 'Run Terraform Init'
            env:
              ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_CONTAINER_NAME: $(ARM_CONTAINER_NAME)
              ARM_RESOURCE_GROUP_NAME: $(ARM_RESOURCE_GROUP_NAME)
              ARM_STORAGE_ACCOUNT_NAME: $(ARM_STORAGE_ACCOUNT_NAME)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
              ARM_VM_PASSWORD: $(ARM_VM_PASSWORD)
          - task: AzureCLI@2
            inputs:
              azureSubscription: PauseClope
              scriptType: ps
              scriptLocation: inlineScript
              inlineScript: |
                Write-Host "Running terraform plan..."
                try {
                  Set-Location -Path terraform
                  terraform plan -out terraform.tfplan `
                    --var="client_id=$env:ARM_CLIENT_ID" `
                    --var="client_secret=$env:ARM_CLIENT_SECRET" `
                    --var="subscription_id=$env:ARM_SUBSCRIPTION_ID" `
                    --var="backend_container_name=$env:ARM_CONTAINER_NAME" `
                    --var="backend_rg_name=$env:ARM_RESOURCE_GROUP_NAME" `
                    --var="backend_account_name=$env:ARM_STORAGE_ACCOUNT_NAME" `
                    --var="backend_access_key=$env:ARM_ACCESS_KEY" `
                    --var="tenant_id=$env:ARM_TENANT_ID" `
                    --var="admin_password=$env:ARM_VM_PASSWORD"
                  Write-Host "Terraform plan completed successfully."
                } catch {
                  Write-Error "Terraform plan failed: $_"
                  exit 1
                }
            displayName: 'Run Terraform Plan'
            env:
              ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_CONTAINER_NAME: $(ARM_CONTAINER_NAME)
              ARM_RESOURCE_GROUP_NAME: $(ARM_RESOURCE_GROUP_NAME)
              ARM_STORAGE_ACCOUNT_NAME: $(ARM_STORAGE_ACCOUNT_NAME)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
              ARM_VM_PASSWORD: $(ARM_VM_PASSWORD)
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: terraform/terraform.tfplan
              ArtifactName: '$(Build.BuildId)-tfplan'
              publishLocation: 'Container'
            displayName: 'Publish Plan Artifact'

  - stage: TerraformApply
    displayName: 'Terraform Apply'
    dependsOn: TerraformPlan
    condition: succeeded()
    jobs:
      - job: TerraformApplyJob
        displayName: 'Apply Terraform Plan'
        steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: '$(Build.BuildId)-tfplan'
              downloadPath: '$(Build.SourcesDirectory)/terraform'
            displayName: 'Download Plan Artifact'

          - task: AzureCLI@2
            inputs:
              azureSubscription: PauseClope
              scriptType: ps
              scriptLocation: inlineScript
              inlineScript: |
                Write-Host "Running terraform apply..."
                try {
                  Set-Location -Path "$(Build.SourcesDirectory)/terraform"
                  terraform apply -auto-approve terraform.tfplan
                  Write-Host "Terraform apply completed successfully."
                } catch {
                  Write-Error "Terraform apply failed: $_"
                  exit 1
                }
            displayName: 'Run Terraform Apply'
            env:
              ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)
              ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
              ARM_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
              ARM_CONTAINER_NAME: $(ARM_CONTAINER_NAME)
              ARM_RESOURCE_GROUP_NAME: $(ARM_RESOURCE_GROUP_NAME)
              ARM_STORAGE_ACCOUNT_NAME: $(ARM_STORAGE_ACCOUNT_NAME)
              ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(AZURE_TENANT_ID)
              ARM_VM_PASSWORD: $(ARM_VM_PASSWORD)