trigger:
- devops

variables:
  TF_ROOT: 'terraform'

stages:
- stage: TerraformPlan
  displayName: 'Terraform Plan'
  jobs:
  - job: Plan
    displayName: 'Run Terraform Plan'
    pool:
      name: Default
    steps:
    - checkout: self

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.6.6'

    - script: |
        terraform init \
          -backend-config="resource_group_name=$(ARM_RESOURCE_GROUP_NAME)" \
          -backend-config="storage_account_name=$(ARM_STORAGE_ACCOUNT_NAME)" \
          -backend-config="container_name=$(ARM_CONTAINER_NAME)" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="access_key=$(ARM_ACCESS_KEY)"
      workingDirectory: $(TF_ROOT)
      displayName: 'Terraform Init'

    - script: terraform plan -out=tfplan
      workingDirectory: $(TF_ROOT)
      displayName: 'Terraform Plan'
      env:
        ARM_CLIENT_ID: $(ARM_AZURE_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_AZURE_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_AZURE_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_AZURE_TENANT_ID)

        TF_VAR_backend_rg_name: $(ARM_RESOURCE_GROUP_NAME)
        TF_VAR_backend_account_name: $(ARM_STORAGE_ACCOUNT_NAME)
        TF_VAR_backend_container_name: $(ARM_CONTAINER_NAME)
        TF_VAR_backend_access_key: $(ARM_ACCESS_KEY)

        TF_VAR_admin_password: $(ARM_VM_PASSWORD)

        TF_VAR_subscription_id: $(ARM_AZURE_SUBSCRIPTION_ID)
        TF_VAR_client_id: $(ARM_AZURE_CLIENT_ID)
        TF_VAR_client_secret: $(ARM_AZURE_CLIENT_SECRET)
        TF_VAR_tenant_id: $(ARM_AZURE_TENANT_ID)

- stage: TerraformApply
  displayName: 'Terraform Apply'
  dependsOn: TerraformPlan
  condition: succeeded()
  jobs:
  - job: Apply
    displayName: 'Run Terraform Apply'
    pool:
      name: Default
    steps:
    - checkout: self

    - script: terraform apply -auto-approve tfplan
      workingDirectory: $(TF_ROOT)
      displayName: 'Terraform Apply'
      env:
        ARM_CLIENT_ID: $(ARM_AZURE_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_AZURE_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_AZURE_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_AZURE_TENANT_ID)

        TF_VAR_backend_rg_name: $(ARM_RESOURCE_GROUP_NAME)
        TF_VAR_backend_account_name: $(ARM_STORAGE_ACCOUNT_NAME)
        TF_VAR_backend_container_name: $(ARM_CONTAINER_NAME)
        TF_VAR_backend_access_key: $(ARM_ACCESS_KEY)

        TF_VAR_admin_password: $(ARM_VM_PASSWORD)

        TF_VAR_subscription_id: $(ARM_AZURE_SUBSCRIPTION_ID)
        TF_VAR_client_id: $(ARM_AZURE_CLIENT_ID)
        TF_VAR_client_secret: $(ARM_AZURE_CLIENT_SECRET)
        TF_VAR_tenant_id: $(ARM_AZURE_TENANT_ID)
