- name: Configure Ubuntu server
  hosts: server
  become: yes
  tasks:
    - name: Install Python (required for Ansible)
      raw: sudo apt-get update && sudo apt-get install -y python3
      changed_when: false

    - name: Gather facts after installing Python
      setup:

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Create .env file
      template:
        src: env.j2
        dest: /home/adminuser/.env
      become: yes
      become_user: adminuser

    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: /home/adminuser/docker-compose.yml
      become: yes
      become_user: adminuser

    - name: Check docker-compose.yml exists
      stat:
        path: /home/adminuser/docker-compose.yml
      register: compose_file

    - name: Debug file presence
      debug:
        var: compose_file.stat.exists

    - name: Start services
      command: docker-compose up -d
      args:
        chdir: /home/adminuser
      become: yes