- name: Configure Ubuntu server
  hosts: server
  become: yes
  tasks:
    - name: Install Python (required for Ansible)
      raw: sudo apt-get update && sudo apt-get install -y python3
      changed_when: false

    - name: Gather facts after installing Python
      setup:

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Create .env file
      template:
        src: env.j2
        dest: /home/adminuser/.env
      become: yes
      become_user: adminuser

    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: /home/adminuser/docker-compose.yml
      become: yes
      become_user: adminuser

    - name: Copy Dockerfile
      copy:
        src: Dockerfile
        dest: /home/adminuser/Dockerfile
        owner: adminuser
        group: adminuser
        mode: '0644'

    - name: Debug Dockerfile presence
      stat:
        path: /home/adminuser/Dockerfile
      register: dockerfile_check

    - name: Debug docker-compose presence
      stat:
        path: /home/adminuser/docker-compose.yml
      register: compose_check

    - debug:
        msg: "Dockerfile exists: {{ dockerfile_check.stat.exists }}, Compose exists: {{ compose_check.stat.exists }}"

    - name: Add adminuser to docker group
      user:
        name: adminuser
        groups: docker
        append: yes
      become: yes

    - name: Start services with Docker Compose (as root)
      shell: sudo docker-compose up -d
      args:
        chdir: /home/adminuser
      become: yes