- hosts: server
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
      become: yes

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
        become: yes

    - name: Create .env file
      template:
        src: env.j2
        dest: /home/user/.env
        become: yes

    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: /home/user/docker-compose.yml
        become: yes

    - name: Start services
      command: docker-compose up -d
      args:
        chdir: /home/user
        become: yes