spring:
  application:
    name: Pause Clope
  datasource:
    url: jdbc:postgresql://localhost:5432/cookieclicker
    username: postgres
    password: password

  data:
    rest:
      base-path: /api/v1